version: "3"
services:
  datascience-notebook:
    build: .
    environment:
      - JUPYTER_ENABLE_LAB=yes
    image: pyspark
    labels:
      description: Pyspark Envoronent
      name: jupyter notebook
    volumes:
      - ./code:/home/jovyan
    ports:
      - 8888:8888
    container_name: tensorflow